services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: pg17_new
    container_name: pg17_ru
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"


  pinger:
    build:
      context: ./pinger
      dockerfile: Dockerfile
    container_name: pinger_service
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always